[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Permissions-Policy = '''
        accelerometer=(none),
        ambient-light-sensor=(none),
        autoplay=(none),
        camera=(none),
        encrypted-media=(none),
        geolocation=(none),
        gyroscope=(none),
        magnetometer=(none),
        microphone=(none),
        midi=(none),
        payment=(none),
        picture-in-picture=(none),
        speaker=(none),
        usb=(none),
        vibrate=(none),
        vr=(none)
    '''

# Configure Netlify builds.
[build]
  publish = "dist/"
  command = "pnpm run build"

# Request bots not to index the admin section.
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Robots-Tag = "noindex"

[[redirects]]
  from = "/p/tl"
  to = "https://github.com/modelorona/TapLock"
  status = 301

[[redirects]]
  from = "/p/si"
  to = "https://github.com/modelorona/Scroll-It"
  status = 301

[[redirects]]
  from = "/p/an2"
  to = "https://github.com/modelorona/Year-5-Dissertation"
  status = 301

[[redirects]]
  from = "/p/an1"
  to = "https://github.com/modelorona/level4dissertation"
  status = 301

[[redirects]]
  from = "/p/bn"
  to = "https://github.com/hkdeman/hacktheburgh2020"
  status = 301

[[redirects]]
  from = "/p/gsc"
  to = "https://github.com/Glasgow19/team-11"
  status = 301

[[redirects]]
  from = "/p/cb"
  to = "https://github.com/modelorona/External-Relations-Chatbot"
  status = 301

[[redirects]]
  from = "/p/xiy"
  to = "https://play.google.com/store/apps/details?id=com.ah.xiny3"
  status = 301