[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Permissions-Policy = '''
        accelerometer=(none),
        ambient-light-sensor=(none),
        autoplay=(none),
        camera=(none),
        encrypted-media=(none),
        geolocation=(none),
        gyroscope=(none),
        magnetometer=(none),
        microphone=(none),
        midi=(none),
        payment=(none),
        picture-in-picture=(none),
        speaker=(none),
        usb=(none),
        vibrate=(none),
        vr=(none)
    '''

# Configure Netlify builds.
[build]
  publish = "dist/"
  command = "pnpm run build"

# Request bots not to index the admin section.
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Robots-Tag = "noindex"