backend:
  name: git-gateway
  branch: main
  repo: modelorona/anguelh.com

publish_mode: editorial_workflow
media_folder: "public/assets/blog"
public_folder: "/assets/blog"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "src/content/blog"
    create: true
    delete: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - {
          name: "pubDate",
          label: "Date",
          widget: "datetime",
          format: "DD MMM YYYY",
          date_format: "DD MMM YYYY",
          time_format: false,
        }
      - { name: "description", label: "Description", widget: "string" }
      - { name: "body", widget: "markdown", label: "Post Body" }
